import { useEffect, useMemo, useState } from "react";
import "./styles.css";

async function fetchJson(path) {
  const response = await fetch(path, { cache: "no-store" });
  if (!response.ok) throw new Error(`${path} failed: ${response.status}`);
  return response.json();
}

function shortHash(value) {
  if (!value) return "—";
  return value.length > 18 ? `${value.slice(0, 10)}…${value.slice(-6)}` : value;
}

function NetworkMap({ nodes, edges }) {
  const positioned = useMemo(() => {
    const width = 900;
    const height = 440;
    const cx = width / 2;
    const cy = height / 2;
    const radius = 165;
    return nodes.map((node, index) => {
      const angle = (index / Math.max(nodes.length, 1)) * Math.PI * 2;
      const typeOffset = node.type === "seller" ? -60 : node.type === "payer" ? 50 : 0;
      return {
        ...node,
        x: cx + Math.cos(angle) * (radius + typeOffset),
        y: cy + Math.sin(angle) * (radius + typeOffset)
      };
    });
  }, [nodes]);

  const byId = new Map(positioned.map((node) => [node.id, node]));

  return (
    <svg className="network" viewBox="0 0 900 440" role="img" aria-label="Agent activity network map">
      {edges.map((edge, index) => {
        const source = byId.get(edge.source);
        const target = byId.get(edge.target);
        if (!source || !target) return null;
        return (
          <line
            key={`${edge.source}-${edge.target}-${index}`}
            x1={source.x}
            y1={source.y}
            x2={target.x}
            y2={target.y}
            className={`edge edge-${edge.type}`}
            strokeWidth={Math.max(1, Math.min(8, Number(edge.events || 1)))}
          />
        );
      })}
      {positioned.map((node) => (
        <g key={node.id} transform={`translate(${node.x}, ${node.y})`}>
          <circle r={node.type === "seller" ? 18 : node.type === "resource" ? 14 : 11} className={`node node-${node.type}`} />
          <text y={node.type === "seller" ? 34 : 28} textAnchor="middle" className="node-label">
            {node.label}
          </text>
        </g>
      ))}
    </svg>
  );
}

function StatCard({ label, value }) {
  return (
    <div className="stat-card">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

export default function App() {
  const [health, setHealth] = useState(null);
  const [nodes, setNodes] = useState([]);
  const [edges, setEdges] = useState([]);
  const [feed, setFeed] = useState([]);
  const [error, setError] = useState(null);

  async function refresh() {
    try {
      setError(null);
      const [healthData, nodeData, edgeData, feedData] = await Promise.all([
        fetchJson("/health"),
        fetchJson("/live/nodes"),
        fetchJson("/live/edges"),
        fetchJson("/live/feed?limit=8")
      ]);
      setHealth(healthData);
      setNodes(nodeData.nodes ?? []);
      setEdges(edgeData.edges ?? []);
      setFeed(feedData.events ?? []);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    }
  }

  useEffect(() => {
    refresh();
    const timer = setInterval(refresh, 4000);
    return () => clearInterval(timer);
  }, []);

  const summary = health?.summary ?? {};

  return (
    <main className="app-shell">
      <section className="hero">
        <div>
          <p className="eyebrow">Portfolio demo</p>
          <h1>AgentsMap Runtime</h1>
          <p className="hero-copy">
            Real-time observability surface for agent economic activity. This public version runs on synthetic local data and demonstrates the API, data model, live updates and network visualization without exposing production worker logic.
          </p>
        </div>
        <button type="button" onClick={refresh}>Refresh</button>
      </section>

      {error ? <div className="error">{error}</div> : null}

      <section className="stats-grid">
        <StatCard label="Sellers" value={summary.sellers ?? 0} />
        <StatCard label="Resources" value={summary.resources ?? 0} />
        <StatCard label="Attributions" value={summary.attributions ?? 0} />
        <StatCard label="Events" value={summary.events ?? 0} />
      </section>

      <section className="panel">
        <div className="panel-header">
          <div>
            <h2>Activity network</h2>
            <p>Synthetic payers, sellers and resources projected as a live graph.</p>
          </div>
          <span className="badge">{health?.mode ?? "loading"}</span>
        </div>
        <NetworkMap nodes={nodes} edges={edges} />
      </section>

      <section className="panel">
        <div className="panel-header">
          <div>
            <h2>Recent payment events</h2>
            <p>Generated by the local demo worker from synthetic seed resources.</p>
          </div>
        </div>
        <div className="feed-list">
          {feed.length === 0 ? (
            <div className="empty">No events yet. Run <code>npm run seed:demo</code> and <code>npm run dev:worker</code>.</div>
          ) : (
            feed.map((event) => (
              <article className="feed-item" key={event.id}>
                <div>
                  <strong>{event.seller_host ?? "Unknown seller"}</strong>
                  <span>{event.method ?? "GET"} {event.resource_url ?? "demo resource"}</span>
                </div>
                <div className="feed-meta">
                  <span>{Number(event.amount ?? 0).toFixed(6)}</span>
                  <code>{shortHash(event.tx_hash)}</code>
                </div>
              </article>
            ))
          )}
        </div>
      </section>
    </main>
  );
}
